#!/usr/bin/env python
import rospy
import controller_manager_msgs.srv
import trajectory_msgs.msg
from std_msgs.msg import String


class move_head():
    def __init__(self):
        #self.quadrant = ""
        self.increment = 0
        self.quad_sub = rospy.Subscriber("quadrant", String, self.move_head)
        #rospy.Timer(rospy.Duration(10), self.move_head())
        self.head_pub = rospy.Publisher('/hsrb/head_trajectory_controller/command',trajectory_msgs.msg.JointTrajectory, queue_size=10)

    def move_head(self,quad):
        quadrant = quad.data
        while self.head_pub.get_num_connections() == 0:
            rospy.sleep(0.1)
        rospy.wait_for_service('/hsrb/controller_manager/list_controllers')
        list_controllers = rospy.ServiceProxy('/hsrb/controller_manager/list_controllers',controller_manager_msgs.srv.ListControllers)
        running = False
        while running is False:
            rospy.sleep(0.1)
            for c in list_controllers().controller:
                if c.name == 'head_trajectory_controller' and c.state == 'running':
                    running = True
        #print("intialized")
        traj = trajectory_msgs.msg.JointTrajectory()
        traj.joint_names = ["head_pan_joint", "head_tilt_joint"]
        p = trajectory_msgs.msg.JointTrajectoryPoint()
        #if q1 q2 etc move robot head
        if quadrant == "q1":
            p.positions = [self.increment, 0.5]
            p.velocities = [0, 0]
            p.time_from_start = rospy.Duration(0.5)
            traj.points = [p]
            self.increment += 0.1
        
        if quadrant == "q2":
            p.positions = [self.increment, 0.5]
            p.velocities = [0, 0]
            p.time_from_start = rospy.Duration(0.5)
            traj.points = [p]
            self.increment -= 0.1
        
        if quadrant == "q3":  
            p.positions = [self.increment, -0.5]
            p.velocities = [0, 0]
            p.time_from_start = rospy.Duration(0.5)
            traj.points = [p]
            self.increment += 0.1  

        if quadrant == "q4":
            p.positions = [self.increment, -0.5]
            p.velocities = [0, 0]
            p.time_from_start = rospy.Duration(0.5)
            traj.points = [p]
            self.increment -= 0.1    
        # publish ROS message

        print("traj", traj)
        self.head_pub.publish(traj)
        #rospy.sleep(3)



def main():
    rospy.init_node('move_head')
    move = move_head()
    #rospy.Timer(rospy.Duration(1/10), move.move_head())
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting Down")



if __name__ == '__main__':
    main()